### ISSUE TITLE
seems like data is not updated if file changed on disk

### ISSUE THREAD

**Issue by chovy** [nikolassilva/nedb-repl#6]
Is there a way to refresh the data?

I have a process writing to my `foo.db` file and i run queries in `nedb-repl` it seems to not pick up new data.

For example running `db.count().exec()` repeated always shows same number but I know there are more documents being added.

**Comment by nikolassilva** [comment]
Hi, @chovy.

Reproduced it by opening the same file with `nedb-repl` in 2 different shells and running some queries, you're right. Maybe I could automatically reload the datastore using `fs.watch`, what are your thoughts?

**Comment by nikolassilva** [comment]
Done! Please update to the latest version, tell me if you find any bugs. Thanks for the issue!
